//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Src\tsql2pgsql\grammar\TSQL.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace tsql2pgsql.grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TSQLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface ITSQLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.dml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDml([NotNull] TSQLParser.DmlContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.xmlWithOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmlWithOption([NotNull] TSQLParser.XmlWithOptionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.alterTableDropConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlterTableDropConstraint([NotNull] TSQLParser.AlterTableDropConstraintContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.convertExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConvertExpression([NotNull] TSQLParser.ConvertExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.selectVariableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectVariableAssignment([NotNull] TSQLParser.SelectVariableAssignmentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerType([NotNull] TSQLParser.IntegerTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.rollbackTransaction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRollbackTransaction([NotNull] TSQLParser.RollbackTransactionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.propertyOrField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyOrField([NotNull] TSQLParser.PropertyOrFieldContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.columnDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnDefinition([NotNull] TSQLParser.ColumnDefinitionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] TSQLParser.TypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.cursorFetch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCursorFetch([NotNull] TSQLParser.CursorFetchContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.alterIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlterIndex([NotNull] TSQLParser.AlterIndexContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.cursorDeallocate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCursorDeallocate([NotNull] TSQLParser.CursorDeallocateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.obscureCommands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObscureCommands([NotNull] TSQLParser.ObscureCommandsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.columnAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnAlias([NotNull] TSQLParser.ColumnAliasContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.dropIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropIndex([NotNull] TSQLParser.DropIndexContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.insertPreamble"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsertPreamble([NotNull] TSQLParser.InsertPreambleContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.transactionIsolationLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransactionIsolationLevel([NotNull] TSQLParser.TransactionIsolationLevelContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] TSQLParser.ArgumentListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.createStatistics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateStatistics([NotNull] TSQLParser.CreateStatisticsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.stringExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExpression([NotNull] TSQLParser.StringExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.setVariableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetVariableAssignment([NotNull] TSQLParser.SetVariableAssignmentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.dropProcedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropProcedure([NotNull] TSQLParser.DropProcedureContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] TSQLParser.UnaryExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.orderByClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderByClause([NotNull] TSQLParser.OrderByClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.updateTop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdateTop([NotNull] TSQLParser.UpdateTopContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.selectListElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectListElement([NotNull] TSQLParser.SelectListElementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.procedureOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureOptions([NotNull] TSQLParser.ProcedureOptionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.qualifiedColumnName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedColumnName([NotNull] TSQLParser.QualifiedColumnNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.procedureParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureParameter([NotNull] TSQLParser.ProcedureParameterContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.minSelectElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinSelectElement([NotNull] TSQLParser.MinSelectElementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.executeArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecuteArgumentList([NotNull] TSQLParser.ExecuteArgumentListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.orderedIndexColumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderedIndexColumn([NotNull] TSQLParser.OrderedIndexColumnContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.insertDataSource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsertDataSource([NotNull] TSQLParser.InsertDataSourceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.xmlDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmlDefinition([NotNull] TSQLParser.XmlDefinitionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.columnIndexOrName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnIndexOrName([NotNull] TSQLParser.ColumnIndexOrNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.likeTestExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLikeTestExpression([NotNull] TSQLParser.LikeTestExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.insertStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsertStatement([NotNull] TSQLParser.InsertStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.deleteTop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteTop([NotNull] TSQLParser.DeleteTopContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.qualifiedNamePart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedNamePart([NotNull] TSQLParser.QualifiedNamePartContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.commitTransaction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommitTransaction([NotNull] TSQLParser.CommitTransactionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompileUnit([NotNull] TSQLParser.CompileUnitContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.updateStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdateStatement([NotNull] TSQLParser.UpdateStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] TSQLParser.FunctionCallContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpression([NotNull] TSQLParser.EqualityExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.intoClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntoClause([NotNull] TSQLParser.IntoClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.procedureParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureParameters([NotNull] TSQLParser.ProcedureParametersContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.forXmlClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForXmlClause([NotNull] TSQLParser.ForXmlClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.alterTableAddConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlterTableAddConstraint([NotNull] TSQLParser.AlterTableAddConstraintContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] TSQLParser.PrimaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.qualifiedColumnNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedColumnNameList([NotNull] TSQLParser.QualifiedColumnNameListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] TSQLParser.AdditiveExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] TSQLParser.RelationalExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tableTargetOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableTargetOptions([NotNull] TSQLParser.TableTargetOptionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.procedureParameterInitialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureParameterInitialValue([NotNull] TSQLParser.ProcedureParameterInitialValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.characterStringType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacterStringType([NotNull] TSQLParser.CharacterStringTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.mergeNotMatched"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMergeNotMatched([NotNull] TSQLParser.MergeNotMatchedContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryBlock([NotNull] TSQLParser.TryBlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.cursorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCursorId([NotNull] TSQLParser.CursorIdContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tableTargetWithOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableTargetWithOptions([NotNull] TSQLParser.TableTargetWithOptionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.deleteStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteStatement([NotNull] TSQLParser.DeleteStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.createProcedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateProcedure([NotNull] TSQLParser.CreateProcedureContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.identitySpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentitySpec([NotNull] TSQLParser.IdentitySpecContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.setStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetStatement([NotNull] TSQLParser.SetStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.existsExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExistsExpression([NotNull] TSQLParser.ExistsExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.overClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOverClause([NotNull] TSQLParser.OverClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.moreInnerJoin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMoreInnerJoin([NotNull] TSQLParser.MoreInnerJoinContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.basicOptionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasicOptionList([NotNull] TSQLParser.BasicOptionListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] TSQLParser.PostfixExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.deleteOutput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteOutput([NotNull] TSQLParser.DeleteOutputContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.havingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHavingClause([NotNull] TSQLParser.HavingClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] TSQLParser.ExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.expressionSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionSet([NotNull] TSQLParser.ExpressionSetContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.fromClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFromClause([NotNull] TSQLParser.FromClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.insertOutputClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsertOutputClause([NotNull] TSQLParser.InsertOutputClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.printExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintExpression([NotNull] TSQLParser.PrintExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.qualifiedNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedNameList([NotNull] TSQLParser.QualifiedNameListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.subSelectExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubSelectExpression([NotNull] TSQLParser.SubSelectExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tempIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTempIndex([NotNull] TSQLParser.TempIndexContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.columnList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnList([NotNull] TSQLParser.ColumnListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.insertValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsertValue([NotNull] TSQLParser.InsertValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.conditionalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalAndExpression([NotNull] TSQLParser.ConditionalAndExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] TSQLParser.MultiplicativeExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.alterTableSwitchPartition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlterTableSwitchPartition([NotNull] TSQLParser.AlterTableSwitchPartitionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.createIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateIndex([NotNull] TSQLParser.CreateIndexContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.columnDefinitionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnDefinitionList([NotNull] TSQLParser.ColumnDefinitionListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] TSQLParser.VariableDeclarationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.procedureBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureBody([NotNull] TSQLParser.ProcedureBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.partitionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartitionName([NotNull] TSQLParser.PartitionNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.mergeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMergeStatement([NotNull] TSQLParser.MergeStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.variableDeclarationAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarationAssignment([NotNull] TSQLParser.VariableDeclarationAssignmentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.updateStatementSetClauseRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdateStatementSetClauseRest([NotNull] TSQLParser.UpdateStatementSetClauseRestContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.joinOrApply"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinOrApply([NotNull] TSQLParser.JoinOrApplyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.orderedIndexColumnList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderedIndexColumnList([NotNull] TSQLParser.OrderedIndexColumnListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.columnName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnName([NotNull] TSQLParser.ColumnNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.executeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecuteArgument([NotNull] TSQLParser.ExecuteArgumentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] TSQLParser.ArgumentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.whereClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhereClause([NotNull] TSQLParser.WhereClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.mergeMatched"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMergeMatched([NotNull] TSQLParser.MergeMatchedContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.partitionIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartitionIdent([NotNull] TSQLParser.PartitionIdentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] TSQLParser.AssignmentOperatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.dmlOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDmlOptions([NotNull] TSQLParser.DmlOptionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tableSourceWithOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableSourceWithOptions([NotNull] TSQLParser.TableSourceWithOptionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tableAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableAlias([NotNull] TSQLParser.TableAliasContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.alterPartitionScheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlterPartitionScheme([NotNull] TSQLParser.AlterPartitionSchemeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.stringValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringValue([NotNull] TSQLParser.StringValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.conditionalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalOrExpression([NotNull] TSQLParser.ConditionalOrExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.characterStringTypeLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacterStringTypeLength([NotNull] TSQLParser.CharacterStringTypeLengthContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.predicateList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicateList([NotNull] TSQLParser.PredicateListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tempTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTempTable([NotNull] TSQLParser.TempTableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementList([NotNull] TSQLParser.StatementListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.groupByClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupByClause([NotNull] TSQLParser.GroupByClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.groupByElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupByElement([NotNull] TSQLParser.GroupByElementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.createIndexPartition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateIndexPartition([NotNull] TSQLParser.CreateIndexPartitionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.integerValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerValue([NotNull] TSQLParser.IntegerValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.selectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectStatement([NotNull] TSQLParser.SelectStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.selectTopLimit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectTopLimit([NotNull] TSQLParser.SelectTopLimitContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] TSQLParser.KeywordContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.waitFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaitFor([NotNull] TSQLParser.WaitForContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tableTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableTarget([NotNull] TSQLParser.TableTargetContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.deleteFromClauseLoose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteFromClauseLoose([NotNull] TSQLParser.DeleteFromClauseLooseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.clusterType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClusterType([NotNull] TSQLParser.ClusterTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.cursorClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCursorClose([NotNull] TSQLParser.CursorCloseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.typeInBracket"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeInBracket([NotNull] TSQLParser.TypeInBracketContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusiveOrExpression([NotNull] TSQLParser.InclusiveOrExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedName([NotNull] TSQLParser.QualifiedNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.xmlDefinitionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmlDefinitionList([NotNull] TSQLParser.XmlDefinitionListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.expressionInRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionInRest([NotNull] TSQLParser.ExpressionInRestContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.commonTableExpressionAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommonTableExpressionAtom([NotNull] TSQLParser.CommonTableExpressionAtomContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.collate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollate([NotNull] TSQLParser.CollateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.dmlOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDmlOption([NotNull] TSQLParser.DmlOptionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusiveOrExpression([NotNull] TSQLParser.ExclusiveOrExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.caseElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseElse([NotNull] TSQLParser.CaseElseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.procedureParameterName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureParameterName([NotNull] TSQLParser.ProcedureParameterNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.raiseError"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaiseError([NotNull] TSQLParser.RaiseErrorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.computeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComputeStatement([NotNull] TSQLParser.ComputeStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.alterTableTrigger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlterTableTrigger([NotNull] TSQLParser.AlterTableTriggerContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tableDeclarationOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableDeclarationOptions([NotNull] TSQLParser.TableDeclarationOptionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.alterTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlterTable([NotNull] TSQLParser.AlterTableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.literalValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralValue([NotNull] TSQLParser.LiteralValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.createTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateTable([NotNull] TSQLParser.CreateTableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.declareStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareStatement([NotNull] TSQLParser.DeclareStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.caseWhen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseWhen([NotNull] TSQLParser.CaseWhenContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.insertValueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsertValueList([NotNull] TSQLParser.InsertValueListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.unaryExpressionNotPlusMinus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpressionNotPlusMinus([NotNull] TSQLParser.UnaryExpressionNotPlusMinusContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] TSQLParser.AndExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.identityType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentityType([NotNull] TSQLParser.IdentityTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.alterPartitionFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlterPartitionFunction([NotNull] TSQLParser.AlterPartitionFunctionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] TSQLParser.StatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.truncateTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTruncateTable([NotNull] TSQLParser.TruncateTableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.setSessionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetSessionParameter([NotNull] TSQLParser.SetSessionParameterContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.cursorStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCursorStatement([NotNull] TSQLParser.CursorStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.dropTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropTable([NotNull] TSQLParser.DropTableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.commonTableExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommonTableExpression([NotNull] TSQLParser.CommonTableExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.selectStatementPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectStatementPart([NotNull] TSQLParser.SelectStatementPartContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionName([NotNull] TSQLParser.FunctionNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalExpression([NotNull] TSQLParser.ConditionalExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tableDeclarationOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableDeclarationOption([NotNull] TSQLParser.TableDeclarationOptionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] TSQLParser.IfStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.ddl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDdl([NotNull] TSQLParser.DdlContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.setSessionOther"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetSessionOther([NotNull] TSQLParser.SetSessionOtherContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] TSQLParser.WhileStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.deleteFromClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteFromClause([NotNull] TSQLParser.DeleteFromClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.setVariableToCursor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetVariableToCursor([NotNull] TSQLParser.SetVariableToCursorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.basicOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasicOption([NotNull] TSQLParser.BasicOptionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.createIndexIncludeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateIndexIncludeList([NotNull] TSQLParser.CreateIndexIncludeListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.selectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectList([NotNull] TSQLParser.SelectListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.orderByElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderByElement([NotNull] TSQLParser.OrderByElementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.transactionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransactionBlock([NotNull] TSQLParser.TransactionBlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.cursorOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCursorOpen([NotNull] TSQLParser.CursorOpenContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.joinType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinType([NotNull] TSQLParser.JoinTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] TSQLParser.VariableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tableSource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableSource([NotNull] TSQLParser.TableSourceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericType([NotNull] TSQLParser.NumericTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.returnExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnExpression([NotNull] TSQLParser.ReturnExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.executeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecuteStatement([NotNull] TSQLParser.ExecuteStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TSQLParser.tableSourceOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableSourceOptions([NotNull] TSQLParser.TableSourceOptionsContext context);
}
} // namespace tsql2pgsql.grammar
